
spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/postgres
    username: ${USER_NAME}
    password: ${USER_PWD}
  jpa:
    hibernate.ddl-auto: create
    defer-datasource-initialization: true

lombok:
  equalsAndHashCode.callSuper: call



