spring:
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:5432/postgres
    username: ${USER_NAME:postgres}
  sql:
    init:
      mode: always
  jpa:
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true



