version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  kpfc_backend:
    container_name: blog_server
    image: blog-backend:local
    ports:
      - 8080:8080
    environment:
      - DB_URL=postgres
      - USER_NAME=postgres
    depends_on:
      - postgres